CREATE TABLE IF NOT EXISTS ALGORITHMS(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS STATUS(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS EXECUTIONS(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    algorithm INTEGER NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    start_time TEXT NOT NULL,
    end_time TEXT NULL,
    result TEXT NULL,
    days_limit INTEGER NOT NULL,
    reads_limit INTEGER NOT NULL,
    times_exceeded_limit INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(status) REFERENCES STATUS(id),
    FOREIGN KEY(algorithm) REFERENCES ALGORITHMS(id)
);
INSERT INTO ALGORITHMS (name)
VALUES ("Ant Colony"), ("Pollination"), ("2-Opt + Ant Colony"), ("2-Opt + Pollination");
INSERT INTO STATUS (name)
VALUES ("EXECUTING"), ("FINISHED"), ("ERROR");